config/routes.rb
Rails.application.routes.draw do
  root                      'static_pages#home'
  get        '/about', to:  'static_pages#about'

  get    '/vestments', to:  'static_pages#vestments'

  get   '/whats_new',  to:  'static_pages#whats_new'

  get     '/contact',  to:  'prospects#new'
  post    '/contact',  to:  'prospects#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prospect.rb
class Prospect < ApplicationRecord
  validates :title, presence:true
  validates :first_name, presence:true, length: {maximum:50}
  validates :second_name, presence:true, length: {maximum:50}
  REGEX_FOR_VALID_EMAIL=/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255}, format: {with: REGEX_FOR_VALID_EMAIL},
                    uniqueness: { case_sensitive: false}

  validates :message, presence:true, length: {minimum:10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  def new
    @prospect=Prospect.new
  end

  def create
    @prospect=Prospect.new(prospect_params)
    if @prospect.save
      #@prospect.send_activation_email
      flash[:success] = "Thanks for getting in touch. We will reply as soon."
      redirect_to root_url
    else
      render 'new'
    end
  end

  private
    def prospect_params
      params.require(:prospect).permit(:title, :first_name, :second_name, :email, :phone_number, :message)
    end
  end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def vestments
  end

  def whats_new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<section class="logo">
  <%= image_tag("swirl.png", :alt => "Swirly title decoration", class: "logo-decoration-l") %>
  <h1>In saecula <br> saeculorum</h1>
  <p>By Sophie Barrett</p>
  <%= image_tag("swirl_r.png", :alt => "Swirly title decoration", class: "logo-decoration-r") %>
</section>

<nav class="nav-bar-top home page">
  <ul>
    <li><%= link_to "Home", root_path %></li><!--
 --><li><%= link_to "Vestments", vestments_path %></li><!--
 --><li><%= link_to "About", about_path %></li><!--
 --><li><%= link_to "What's New", whats_new_path %></li><!--
 --><li><%= link_to "Contact", contact_path %></li>
  </ul>
</nav>

<section class="row quote">

  <div class="col-md-12 quote-box">
    <p class="big-quote">"Bespoke vestments, made to measure..."</p>
  </div>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title)%> | In Saecula Saeculorum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Cinzel|Playfair+Display:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
  </head>

  <body>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/prospects/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/prospects/new.html.erb
<% provide(:title, "Contact")%>

<%= form_for(@prospect, url:contact_path) do |f| %>
<%= render 'prospects/error_messages', object: f.object %>
   <%= f.label  :first_name %>
   <%= f.text_field  :first_name %>

   <%= f.label :title %>
   <%= f.text_field :title %>

   <%= f.label :second_name %>
   <%= f.text_field :second_name %>

   <%= f.label  :email %>
   <%= f.email_field :email %>

   <%= f.label :phone_number %>
   <%= f.text_field :phone_number %>

   <%= f.label :message %>
   <%= f.text_field :message %>

   <%= f.submit %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About")%>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home")%>


  <section class="row first">

    <div class="col-md-6 photo-box">
      <div class="photo">
        <%= image_tag("1.jpg", :alt => "vestment", class: "feature-img") %>
      </div>
    </div>

    <div class="col-md-6 text-box">
      <div class="text">
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
      </div>
    </div>

  </section>

  <section class="row second">

    <div class="col-md-6 text-box">
      <div class="text">
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
      </div>
    </div>

    <div class="col-md-6 photo-box">
      <div class="photo">
        <div class="photo">
          <%= image_tag("10.jpg", :alt => "vestment", class: "feature-img") %>
        </div>
      </div>
    </div>

  </section>

  <section class="row third">

    <div class="col-md-6 photo-box">
      <div class="photo">
        <div class="photo">
          <%= image_tag("4.jpg", :alt => "vestment", class: "feature-img") %>
        </div>
      </div>
    </div>

    <div class="col-md-6 text-box">
      <div class="text">
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
      </div>
    </div>

  </section>

app/views/static_pages/vestments.html.erb
<% provide(:title, "Vestments")%>
<h1>StaticPages#vestments</h1>
<p>Find me in app/views/static_pages/vestments.html.erb</p>

app/views/static_pages/whats_new.html.erb
<% provide(:title, "What's New")%>
<h1>StaticPages#whats_new</h1>
<p>Find me in app/views/static_pages/whats_new.html.erb</p>